name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      # 拉取代码
      - uses: actions/checkout@v4

      # 部署到 Azure Static Web Apps
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_543_TOKEN }} # 你的 Azure token secret
          repo_token: ${{ secrets.GITHUB_TOKEN }}                          # 不用改
          action: "upload"
          app_location: "/"        
          api_location: ""        
          output_location: ""     

          